export const SET_CONTACT = "SET_CONTACT";
export const REMOVE_CONTACT = "REMOVE_CONTACT";
export const EDIT_CONTACT = "EDIT_CONTACT";
export const ADD_FAVOURITE = "ADD_FAVOURITE";

export const SET_GROUP = "SET_GROUP";
export const REMOVE_GROUP = "REMOVE_GROUP";
export const GET_GROUP = "GET_GROUP";
export const EDIT_GROUP = "EDIT_GROUP";

export const ADD_REMOVAL_QUEUE = "ADD_REMOVAL_QUEUE";
export const QUEUE_UNDO = "QUEUE_UNDO";
export const CLEAN_QUEUE = "CLEAN_QUEUE";

export const ADD_REMOVAL_QUEUE_GROUP = "ADD_REMOVAL_QUEUE_GROUP";
export const QUEUE_UNDO_GROUP = "QUEUE_UNDO_GROUP";
export const CLEAN_QUEUE_GROUP = "CLEAN_QUEUE_GROUP";

export const SELECT_CONTACT = "SELECT_CONTACT";
export const SELECT_ALL_CONTACT = "SELECT_ALL_CONTACT";
